name: deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DETA_ACCESS_TOKEN: ${{ secrets.DETA_ACCESS_TOKEN }}
      DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
      VK_GROUP: ${{ secrets.VK_GROUP }}
      VK_TOKEN: ${{ secrets.VK_TOKEN }}
      VK_CONFIRMATION: ${{ secrets.VK_CONFIRMATION }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      VIBER_TOKEN: ${{ secrets.VIBER_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Deta CLI
      run: |
        curl -fsSL https://get.deta.dev/cli.sh | sh
    - name: Deploy
      run: |
        ~/.deta/bin/deta clone --name botcom --project BotCom tmp/
        cp -r tmp/.deta botcom/
        cp requirements.txt botcom/
        ~/.deta/bin/deta deploy botcom
    - name: Set up environment variables
      run: |
        cd botcom
        echo DETA_PROJECT_KEY=$DETA_PROJECT_KEY >> .env
        echo VK_GROUP=$VK_GROUP >> .env
        echo VK_TOKEN=$VK_TOKEN >> .env
        echo VK_CONFIRMATION=$VK_CONFIRMATION >> .env
        echo TELEGRAM_TOKEN=$TELEGRAM_TOKEN >> .env
        echo VIBER_TOKEN=$VIBER_TOKEN >> .env
        ~/.deta/bin/deta update --env .env
